---
abstract: 'Apply roles to action instances'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091940'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-ActionRole
requires:
  Catalyst::Runtime: 5.71001
  Class::MOP: 0.80
  Moose: 0.70
  MooseX::Types::Moose: 0
  String::RewritePrefix: 0.004
  namespace::clean: 0
version: 0.12
