---
abstract: 'Apply roles to action instances'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-ActionRole
recommends: {}
requires:
  Catalyst::Runtime: 5.71001
  Class::MOP: 0.80
  Moose: 0.90
  MooseX::Types::Moose: 0
  String::RewritePrefix: 0.004
  namespace::clean: 0
resources:
  repository: git://github.com/rafl/catalyst-controller-actionrole.git
version: 0.14
